### ISSUE TITLE
Errors while building for PHP-5.3

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [pierrejoye/php_zip#13]
System: Ubuntu 14.04 x86
PHP: 5.3.29
Previous version 1.13.2 builded without errors.

Build output:
```
libtool: compile:  cc -I. -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src -DPHP_ATOM_INC -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/inclu
de -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/main -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src -I/usr/include/php53 -I/usr/include/ph
p53/main -I/usr/include/php53/TSRM -I/usr/include/php53/Zend -I/usr/include/php53/ext -I/usr/include/php53/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/sergey/debuild-
php-modules/php-mod-zip/php-mod-zip-1.13.3/src/lib -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5 -DHAVE_CONFIG_H -g -O2 -fstack-protector --param=ssp-buffer-
size=4 -Wformat -Werror=format-security -O2 -pipe -D_FORTIFY_SOURCE=2 -c /home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5/php_zip.c  -fPIC -DPIC -o php5/.libs/php
_zip.o
libtool: compile:  cc -I. -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src -DPHP_ATOM_INC -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/inclu
de -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/main -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src -I/usr/include/php53 -I/usr/include/ph
p53/main -I/usr/include/php53/TSRM -I/usr/include/php53/Zend -I/usr/include/php53/ext -I/usr/include/php53/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/sergey/debuild-
php-modules/php-mod-zip/php-mod-zip-1.13.3/src/lib -I/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5 -DHAVE_CONFIG_H -g -O2 -fstack-protector --param=ssp-buffer-
size=4 -Wformat -Werror=format-security -O2 -pipe -D_FORTIFY_SOURCE=2 -c /home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5/zip_stream.c  -fPIC -DPIC -o php5/.libs/
zip_stream.o
/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5/php_zip.c: In function 'php_zip_add_from_pattern':
/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5/php_zip.c:1835:7: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'size_t' [-W
format=]
       MAXPATHLEN - 1, (add_path_len + file_stripped_len));
       ^
/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5/php_zip.c: In function 'zm_startup_zip':
/home/sergey/debuild-php-modules/php-mod-zip/php-mod-zip-1.13.3/src/php5/php_zip.c:3159:21: error: 'zend_object_handlers' has no member named 'get_gc'
  zip_object_handlers.get_gc          = php_zip_get_gc;
                     ^
make[1]: *** [php5/php_zip.lo] Error 1
```

**Comment by sergey-dryabzhinsky** [comment]
Builds fine with PHP-5.4.45
